### ISSUE TITLE
Getting Assertion "Every week should have games except for a week 1 exception"

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#71] opened 2015-08-28 12:25 UTC
This assertion occurs if a commissioner has posted the createweek URL but has not posted the editweek URL successfully with valid games. There are two problems here.

Problem 1:
The message says "week 1 exception", but in this case it was actually week 2 that had no Games. I don't know if the exception message was intended to point out exactly which week was in error, but if so, it should have said "week 2 exception" and it probably should also indicate the Year.

Problem 2:
The exception is actually premature because this is a temporary state. Because there are two URLs involved it is possible that a commissioner might post the createweek URL and then delay for any number of reasons before posting the editweek URL. We do have protection provided by the Week.lock_picks flag. When the createweek URL is posted, Week.lock_picks is set to True. So, I would recommend that this assertion include not Week.lock_picks as part of its asserted condition.

Furthermore, this might also mean that any Week that has lock_picks set to True, should be skipped from displaying on the results pages as if it does not exist.

![image](https://cloud.githubusercontent.com/assets/5880937/9546125/1785a882-4d5e-11e5-8da9-ac6b8619f129.png)

**Comment by jbholden** [comment] 2015-08-28 17:27
The problem is that the code expects every week except for week 1 to have games.  For the player results page, if there are no games then there is nothing to show yet.    As a side effect, I believe that if the last week is in this state (i.e. no games), then the get_pool_state() function will fail when called which will mess up all the other weeks in that year.  Here is the snippet of failing code.

```Python
        week = self.__get_week_in_database(year,week_number=last_week_number)
        week_has_no_games = self.__week_has_no_games(year,last_week_number)

        only_week_one_exists = last_week_number == 1 and len(week_numbers) == 1

        if only_week_one_exists and week_has_no_games:
            return "not_started"

        assert not(week_has_no_games),"Every week should have games except for a week 1 exception"

        if self.__before_pick_deadline(week):
            return "enter_picks"
```

The current pool states are
```Python
List of Pool States
# these 1st 2 states represent beginning and end of the pool
'not_started'    #  pool not started, year has week 1 model, but no games yet
'end_of_year'  #  week 13 is FINAL

# these states get cycled thru each week
'enter_picks'  # week exists but before pick deadline
'week_not_started'  # last week in NOT_STARTED state
'week_in_progress' # last week in IN_PROGRESS state
'week_final'  #  if not week 13, last week in FINAL state
```

I would recommend adding another state like 'week_setup' that is valid when there is a week in the database, and there are no games for the week or the picks are locked.  Then updating the pages to check for this state and display an appropriate message (player results would display something like "the week" is being setup).

```Python
New Pool States
'not_started'    #  pool not started, year has week 1 model, but no games yet
'end_of_year'  #  week 13 is FINAL

# these states get cycled thru each week
'week_setup'   # week games are being setup
'enter_picks'  # week exists but before pick deadline
'week_not_started'  # last week in NOT_STARTED state
'week_in_progress' # last week in IN_PROGRESS state
'week_final'  #  if not week 13, last week in FINAL state
```

```Python
# code to add week_setup state
 if only_week_one_exists and week_has_no_games:
    return "not_started"

#remove this
#assert not(week_has_no_games),"Every week should have games except for a week 1 exception"

if week_has_no_games:
    return "week_setup"

if self.__before_pick_deadline(week) and week.lock_picks:
    return "week_setup"

if self.__before_pick_deadline(week):
    return "enter_picks"
```

I can make the change if you agree to this new state.

**Comment by blreams** [comment] 2015-08-28 18:43
I'm definitely OK with this. Go ahead and make it so. I think this is totally encapsulated in the database.py module. Since this doesn't affect pick10/models.py, feel free to commit this to master once you have it implemented/tested, and close this issue.

**Comment by jbholden** [comment] 2015-08-29 19:03
The code has been committed to the master branch.

**Closed by jbholden** 2015-08-29 19:03 UTC
Labels: bug
