### ISSUE TITLE
Email reminder to enter picks before deadline

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#107] opened 2016-09-26 19:58 UTC
It seems like it would be a good idea to setup some sort of email reminder to enter picks.  I think the following might work.

- create a python script that finds all the people that haven't entered picks, and send an email reminder to them
- Setup a "scheduled task" in PythonAnywhere to run this script about 1 hour before the pick deadline
- When the pick deadline is setup for the week, setup the time for this scheduled task as well

**Comment by jbholden** [comment] 2016-09-27 21:04
I created a script to email a pick reminder and committed it to github.
I need your help to test this script out to see if it works.

The script is called email_players_with_no_picks.py and is in the root directory.

Specifically, can you:
- Upload the script to the collegefootballpick10 site
- Under the schedule tab add the path to this script and trigger it a few hours from now (need to convert to UTC time)

The script that was committed was set to send an email to my gmail and to your gmail address with a list of the players that haven't made picks yet.  We'll see if this works.

**Comment by blreams** [comment] 2016-09-28 00:51
I just set it up to run at 01:00 UTC (9:00pm EDT).

**Comment by jbholden** [comment] 2016-09-28 02:00
Yes, I forgot to check that in.  I'll check it in tomorrow and then see if that works.  You are only allowed to run a scheduled script once daily.

**Comment by blreams** [comment] 2016-09-28 10:53
True, but I can run it manually for testing.

**Comment by jbholden** [comment] 2016-09-28 17:26
**Script Checked In**
I have checked in the required files to github.  When you get a chance can you update the site and try running the script? Or just wait for the schedule to trigger the script? 

I took a quick look at the last run on pythonanywhere.com and the log complained about django.setup().  This was required to run it from the command line, so I'm not sure if this is required or not.

**Questions**
I have a few questions (you may or may not have the answer to)
- What happens when this script runs and generates an error (just shows up in log? is the site ok?)
- What happens when you print inside the script (does this go to the log?)
- Is there a limit to the number of emails that can be sent?

**Features**
I am envisioning that the script would do something like this
- Send a separate email to each individual that has not entered picks
- Inside the email, provide a link to the picks page for that individual
- Send another email to the commissioners showing people that haven't entered picks (so that they would know that an email reminder was sent out)
- The commissioners also need to ensure the schedule time is set appropriately each week (3:00 EDT would probably work most weeks, but this week for example, might want to set it to 5:00 EDT or 8:00 EDT)

**Comment by blreams** [comment] 2016-09-28 21:30
Appears to be working now with your latest commits. Here are my answers to the above questions.

- When the script runs and generates an error, it will show up in the schedule log. The site should be ok unless the script does something that corrupts the database (unlikely).
- When you print inside the script...not sure...but we will find out in a few minutes (I set it to run today at 5:30pm EDT).
- There is a limit to the number of emails, but I'm not sure what the limit is. I'd say go ahead and implement your plan and if we hit the limit...the worst that will happen is emails won't go out.

This last brings up a good point. Right now you can schedule a task to run every day at the same time. We really only want to send reminder emails the day of the pick deadline, so I would suggest adding some additional checking in the script to see if today is the pick deadline. If not, exit.

**Comment by blreams** [comment] 2016-09-28 21:45
OK, the script still failed as a scheduled task::

    Traceback (most recent call last):
      File "/home/collegefootballpick10/collegefootballpick10/email_players_with_no_picks.py", line 9, in <module>
        django.setup()
    AttributeError: 'module' object has no attribute 'setup'

The problem is that we need to specify the correct python and django versions that are used in the virtualenv that the site uses.

I created a bash script called pick_reminder.sh to do just that...will run at 5:45pm EDT.

**Comment by blreams** [comment] 2016-09-28 21:58
OK, that didn't quite work, because we actually need to use the virtualenv which has a number of necessary environment variables set.

Trying again at 6:00pm EDT, this time using a python script that activates the virtualenv and then runs your script as a subprocess.

**Comment by jbholden** [comment] 2016-09-28 22:10
Once the SCRIPT_TEST is set to false in the script, then it will only send emails if the current time is within 24 hours of the pick deadline.

I'm a little confused about what has been run.  I have received 4 emails from the script.  Have you been running it manually at all?  Or is the scheduled task successfully sending emails even though there is a Django error?

**Comment by blreams** [comment] 2016-09-28 22:12
I'm still working out the kinks in the pick_reminder.py script. It works when I run it manually, but when I schedule it, it keeps complaining about the #! line I'm using to invoke python as the script interpreter.

I've run it several times manually which is why you have received several emails.

**Comment by blreams** [comment] 2016-09-28 22:40
Finally, I got it working. I'm going to schedule it to run at 3:00pm EDT everyday. It would be cool if we could get it send the reminder emails in time for the deadline this week.

**Comment by blreams** [comment] 2016-09-28 22:40
BTW, you should have gotten an email that was sent at 6:36pm EDT that was the result of the scheduled task.

**Comment by jbholden** [comment] 2016-09-28 23:17
I'll finish the script tomorrow, which should give enough time for it to run on Friday at 3:00 PM.

I received an email at 6:36 PM.

**Comment by jbholden** [comment] 2016-09-29 17:53
The script is now ready to run.  I made a lot of changes though, but I think it should still work.
We'll see if it runs tomorrow at 3 PM.  Also, after it runs it might be a good idea to check with someone on the email list to see if they got an email.

Running it manually won't work at this point because it won't trigger unless it is run after 9 PM tonight because of the pick deadline.  If it is run manually after 9 PM, it would send reminder emails to everyone that haven't entered picks yet.

**Comment by blreams** [comment] 2016-09-29 21:11
I'm trying to figure out what the scheduled time should be that would accomodate most pick deadlines. BTW, this week I set the pick deadline to be the same as the earliest kick-off. Typically, the earliest game kick-off time in any given week will be Noon, 3:30pm, 7:00pm, 8:00pm. I'm thinking I will set the schedule to run this script at 2:00pm. Doing that will yield the following times when the pick reminder is emailed:

1. Pick deadline Thursday at 7:00pm --> pick reminder Thursday at 2:00pm
2. Pick deadline Friday at 8:00pm --> pick reminder Friday at 2:00pm
3. Pick deadline Saturday at Noon --> pick reminder Friday at 2:00pm

**Comment by blreams** [comment] 2016-09-30 19:25
Looks like it worked. The following was in the Schedules log:
Finding players with no picks for 2016 week 5
Sending reminder email to cabarker@yahoo.com
Sending reminder email to justin.t.gilmer@intel.com
Sending reminder email to tqn2006@gmail.com
Sending reminder email to lamarpowell@gmail.com
Sending reminder email to staub@yahoo.com

2016-09-30 18:03:32 -- Completed task, took 54.00 seconds, return code was 0.

Also, I received an email saying who was getting the emails.

I also checked with a couple folks who were sent emails and they all said they got it.

One last change I would suggest. Instead of emailing me and you the heads-up, it should send that email to Users who are Staff (ie. commissioners).

**Comment by jbholden** [comment] 2016-09-30 20:08
I wasn't quite sure how to detect staff users, so for this week I just hardcoded your email and my email address.  I did a little google searching and I think a function like this might work.  All the commissioners are identified by the superuser right?

```
from django.db.models import Q    

def get_staff():
   return User.objects.filter(Q(is_superuser=True))
```

**Comment by blreams** [comment] 2016-09-30 21:18
That should work.

When I first setup the commissioners, I gave them staff permissions but not superuser permissions. That allowed them to access the Admin interface, but they couldn't modify any of the model tables. Rather than go through and give them individual permissions for each table, I gave them superuser permissions.

However, I'm thinking about demoting them back to staff permissions and then allow them add/edit/delete permission for the various tables they might need to modify.

So, I would rather you use is_staff() than is_superuser().

**Comment by jbholden** [comment] 2016-10-01 17:59
The picks reminder script has been updated to use the is_staff field for admin email addresses.

I'm not sure how the database is set up, but I believe that a user marked as a superuser but not staff would not receive the email.  Do you want superusers as well as staff to get the email?

Also, I don't think I am marked as staff in the database (not sure).  I would like to see the email though.  Should I hardcode my address or can you check that I get marked as staff in the database?

One other issue is that looking into the code, is_superuser is used in several places instead of is_staff.  For example, only a superuser can lock the game scores for the week on the game scores page.  Does this need to be changed to staff?

**Comment by blreams** [comment] 2016-10-02 04:27
All of the staff accounts are separate from regular user accounts. IOW, I have one account that I use to make picks that does not have staff permissions. I have a second commissioner account that is not linked to any Player, and that account does have staff permission. It is the same for the other commissioners. If you want staff permission, then I would ask you to register a second account for that.

Also, I don't think locking game scores should be a superuser permission...it should be a staff permission. I can't really think of anything that should be superuser only.

**Comment by blreams** [comment] 2016-10-29 15:30
I'm going to close this issue. I believe the original intent has been addressed with the scheduled script that runs daily.

**Closed by blreams** 2016-10-29 15:30 UTC
Labels: enhancement, help wanted
